### ISSUE TITLE
a few hardcoded references to table 'sessions' in index.js

### ISSUE THREAD

**Issue by Pollocks01** [Slumber86/express-oracle-session#2]
Just letting you know that you have 2 hardcoded reference to 'sessions' table name in index.js version 0.1.2.

**Comment by Slumber86** [comment]
Thanks, fixed it.. doing a release soon..

**Comment by Pollocks01** [comment]
That's awesome!

Don't suppose you also want to allow passing of poolAlias in the options? You pull from 'default' pool but it'd be really easy to use the passed poolAlias if set, otherwise use 'default'.
