### ISSUE TITLE
Enforce ARRAY outFormat

### ISSUE THREAD

**Issue by fhahne** [Slumber86/express-oracle-session#5]
Great module. One small tweak: could you enforce outFormat: oracledb.ARRAY for all the execute calls that rely on arrays as return value? I am running the store in a context where the global outFormat of the oracledb module gets overwritten, and thus the parsing of the session string fails.
E.g., in row 144 of index.js:
this.connection.execute(sql, params, { fetchInfo: { "DATA": { type: oracledb.STRING} } },
instead, use
this.connection.execute(sql, params, { outFormat: oracledb.ARRAY, fetchInfo: { "DATA": { type: oracledb.STRING} } },
Thanks,
Florian

**Comment by Slumber86** [comment]
I have relased a new version fixing this bug, try it out
